### PR TITLE
Add /packages directory

### PR DESCRIPTION
**Pull request by craiglabenz**
As preparation for generated route helpers, I've moved all of the relevant package code into `/packages/go_router`. The plan is to land on the following structure:

```
/packages
  /go_router
  /go_router_annotation
```

There is not likely any good reason to merge this until the follow-up `go_router_annotation` PR is approved; but this is in place to start any package layout discussions and keep the builder / annotation changes more easily read.

The conversation for this started in #66.

### CODE REVIEW

**Comment by kevmoo** [comment]
My vote: don't add `packages` unless there will be a lot

It's often nicer to have everything at the root – IMHO

I prefer https://github.com/dart-lang/build to https://github.com/dart-lang/test

Just my taste, though 😄

**Comment by csells** [comment]
Yeah. This one needs revisiting.

**Comment by craiglabenz** [comment]
FWIW, my inspiration for this idea was [Freezed's setup](https://github.com/rrousselGit/freezed/tree/master/packages), which allows for keeping `freezed` (all of the codegen) as a dev dependency, and only requires `freezed_annotation` to be an actual production dependency.

**Comment by kevmoo** [comment]
Totally agree with the split.  Just my taste is to not make an extra layer
of directories

**Pull request closed without merging**
