### PR TITLE
Constructor comes first

### PR DESCRIPTION
**Pull request by Abhishek01039**
DO sort constructor declarations before other members.

https://dart-lang.github.io/linter/lints/sort_constructors_first.html

### CODE REVIEW

**Comment by Abhishek01039** [comment]
Hello @csells 
can you please review this PR?
Thanks

**Comment by csells** [comment]
@Abhishek01039 I appreciate the enthusiasm. Can I ask why it matters if the constructors come first in the implementation or sample code? Users still have the exact some experience either way...

**Comment by Abhishek01039** [comment]
My intention is to follow the best practices.

**Comment by csells** [comment]
Well, @Abhishek01039, if it makes you happy, it makes me happy. : )

**Comment by Abhishek01039** [comment]
Thank you @csells

**Pull request merged**
